<?php

namespace Assurance\FrontBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * annee_constructionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class annee_constructionRepository extends EntityRepository
{
}
