<?php

namespace Assurance\FrontBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Annee_circulationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Annee_circulationRepository extends EntityRepository
{
}
