<?php

namespace Assurance\FrontBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * KilometrageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KilometrageRepository extends EntityRepository
{
}
