<?php

namespace Assurance\FrontBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ModeleaudiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModeleaudiRepository extends EntityRepository
{
}
